### PR TITLE
ScreenOneActivity revamped

### PR DESCRIPTION
**Pull request by ananthrajsingh**
@abha1376 This makes the ScreenOne of your app better looking. Have a look and merge if you like. Also, your google login is buggy, MainActivity takes directly to ScreenOne for now.

### CODE REVIEW

**Comment by abha1376** [comment]
hey i am having an error in the questions fragment in which i will pass the questions chapterwise in an arraylist and wants to check those questions...like when we click on an option it should show the color change red and green ...so can u do that?

**Comment by abha1376** [comment]
and no need to remove google login.

**Comment by abha1376** [comment]
thanks for the layout

**Comment by ananthrajsingh** [comment]
Okay I'll have a look at that. I removed (temporarily) just by changing Intent call in MainActivity. You can have it back easily. But it was hindering proper functioning of application.

**Comment by abha1376** [comment]
Yup thanks...pls tell me asap as soon as you are done....

Sent from Mail for Windows 10

**Comment by ananthrajsingh** [comment]
So you want it to change colour the same way it does in TestSeries Activity?

**Comment by abha1376** [comment]
Yes the same way I want to change the color and I need to figure out ..how to send questions chapterwise in an array.

Sent from Mail for Windows 10

**Comment by ananthrajsingh** [comment]
I have already done that colour changing stuff. You can check it in the other Pull Request. I have also sent you the mail of screenshot. Please elaborate on chapter wise feature.

**Comment by abha1376** [comment]
In chapter wise feature...when someone clicks on chapter one...then just
the way I send videos through an array list...I will send questions in that
way to an empty arraylist in question fragment..

**Comment by ananthrajsingh** [comment]
I think you should give me access to your repository. Then we can create separate branch and work on respective branches. master branch should not be disturbed this often.

**Comment by ananthrajsingh** [comment]
Under your repository name, you'll have an option of **Settings**. In the left sidebar, click **Collaborators** . Then Add me as collaborator. :)

**Comment by abha1376** [comment]
Actually I am working in modules...that's not my complete project...
therefore I would be having no problem in merging ur pull requests...so u
can work on it and send me...I will simply merge and check..if it will
work...I will copy it in my Main project...that would be helpful from ur
side

**Comment by ananthrajsingh** [comment]
I am happy to wilfully help and contribute in your project. But there is a communication barrier. I can figure out how to show videos in the video fragment. The ways I'm suggesting will improve your GitHub skills too. Well, if you say so I can work as it is. You know, communicating this way, I can develop some feature but it may be not according to your requirement. Then the work will go in vain. I hope you figure out some better way to convey your requirements. 👍 :)

**Comment by abha1376** [comment]
Hey thanks.....I already completed on stuff how to transfer video in
fragment...I just need to work on that question portion in that question
fragment only ....and yeah... .I attached your layout in my main project
...it's nice .thanks..I want the same type theme in every activity.. n
actually right now I m not near my lappy...so will Chk that Color change
stuff till 8....if its good
..I will attach it n will upload the project...so that u cn understand it
in a more convenient way...

**Comment by ananthrajsingh** [comment]
Just tell me **in detail** what you want from that question fragment. I'd be happy to help in your project. Also, I'll try to design new layouts for activities.

Would you mind my asking, that what is the purpose of this project? I mean is this for your college project, or you want it tor your resume, or you have internal motivation?

**Comment by abha1376** [comment]
This is my own project to provide study material to IIT aspirants and other
engineering exams...I already have the material and chapterwise questions
,daily practice papers etc ..
Take a look at an app JEE FOCUS.... download it...u will know what I am
preparing

**Comment by ananthrajsingh** [comment]
You checked the Question fragment?

**Comment by abha1376** [comment]
Currently doing it but your changes are not working...i tried it on my phone

Sent from Mail for Windows 10

**Comment by ananthrajsingh** [comment]
oops! I sent you the screenshot on mail. Working on my phone.

**Comment by abha1376** [comment]
I didn’t receive it.....just a moment please I guess I made a mistake..just wait I will mail u back

Sent from Mail for Windows 10

**Comment by abha1376** [comment]
In fragment ques I am getting error in @override...what to do? I simply copied yours

Sent from Mail for Windows 10

**Comment by ananthrajsingh** [comment]
[https://drive.google.com/open?id=10Rw7tHwcYk1iMVYC2Yss-OSxD436Jvzk](See this Image Abha)

**Comment by ananthrajsingh** [comment]
Abha, Simply copying won't work. I changed multiple files for this feature.

**Comment by abha1376** [comment]
Hey you made changes only in adapter and fragment question ...right?

Sent from Mail for Windows 10

**Comment by abha1376** [comment]
So I need to merge?
Everything?

Sent from Mail for Windows 10

**Comment by ananthrajsingh** [comment]
This is what I was talking about. Copy paste is not the right way of doing it.

**Comment by abha1376** [comment]
Ok I am merging 😊

Sent from Mail for Windows 10

**Comment by ananthrajsingh** [comment]
Though you are merging it. But merging in the **master** is not a good idea. That is why I was you to add me as a moderator.I'll handle these things, as I'm experienced. Also,  you merged the wrong pull request. That new feature is in Pull Request #2

**Comment by ananthrajsingh** [comment]
Okay you merged both! Okay then

**Pull request merged**
